<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Render\Element\RenderElement;
use Drupal\Core\Render\Element\RenderableInterface;
use Drupal\Core\Render\Element\FormElement;

/**
 * Implements hook_theme().
 */
function devspring_theme($existing, $type, $theme, $path)
{
  return [
    'gen_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'about_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'footer_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'subheader_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'ready_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'related_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'information_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'opinion_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    ];
}
